name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: build with maven
        run: ./mvnw -B package

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: logolas
        run: echo "Logolas"

  build-images:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: build images
        run: echo "build image here"

  deploy:
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: deploy
        run: echo "deploy here"
